title: "JS Coding Blog"
description: "자바스크립트 코딩테스트 문제, JS 알고리즘 연습, JavaScript 메서드 학습 문제를 카테고리별로 풀어볼 수 있는 코테 로그"
lang: ko-KR
timezone: Asia/Seoul
baseurl: ""
url: "https://js-coding.sooyadev.com"
markdown: kramdown
permalink: pretty

collections:
  problems:
    output: true
    permalink: /problems/:name/

defaults:
  - scope:
      path: ""
      type: "problems"
    values:
      layout: problem

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

disqus:
  shortname: js-coding
